### ISSUE TITLE
Wrong comment field in wallet history

### ISSUE THREAD

**Issue by echupriyanov** [stegos/stegos#1046]
```
    - Incoming:
        timestamp: "2019-06-26T15:06:30.226750000Z"
        output:
          Payment:
            utxo: 8d16b584bfa53d98b16b566a58aaa7583468066ee33355ba86696d3d8fcc1b5e
            amount: 40000000
            data:
              Comment: test
            locked_timestamp: ~
```
Comment should be "Block reward + fee"
