### ISSUE TITLE
Stake transaction doesn't have `outputs` in history

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#1180]
stake 2000
```
    - type: outgoing
      timestamp: "2019-07-29T13:58:39.252662904Z"
      tx_hash: 1fb7cf751de0b9b8f341a9d27b55267811e3c995a62918e3568d8b321216d546
      fee: 1000
      inputs:
        - 2abace32ef52badcf33d3ab72f9392f9c9abae6147bbc6415b3a9d95685f4891
        - 1ff70304b8b03536c6e324fae6de53a74d06d17e455e81376b3e61038a75dd31
        - 17ba565c0fcc09388461a2d60aa1cea747a92e3caef685abb2553c4a289d4161
        - 5057bd14486c9115cd9392b841399d3a180d1671a46751158f4f05ca30663514
        - d254d75ed90a9a5104d059170bbbee5bed61154a4feb9a9c2817d7c5b7789c01
      status: prepared
      epoch: 867
      offset: 4
```
