### ISSUE TITLE
Missing output in `unstake` response

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#1273]
I had 1M tokens, but don't this 1M in `outputs:`:

```
account#1> unstake                                                                                                                                                                                      
---                                                                                                                                                                                                     
- type: unstake_all
  payment_fee: 1000
...

---
- account_id: "1"
  type: transaction_created
  tx_hash: 6896c77a9f5c73e034477552e215643dbff45f5014914275327191d608fec1c0
  fee: 1000
  outputs:
    - output_type: payment
      utxo: 7a024899114aaa11bc536b8a506e17e3d8cfae919e545a8e5a04f850888b5088
      amount: 0
      comment: Change for stake.
      locked_timestamp: ~
      recipient: 7ewZB7ECBkEgBaug1uPLXV8X4S3Beo3P7RgDA3PaFSjdVh5eDMu
      is_change: false
  inputs:
    - 21d6e2e56841bea0439e683d3df37c89ce73bf7e6d5a063953e073593b1a866c
  status: created
```
