### ISSUE TITLE
Invalid value of `is_change` flag

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#1275]
```
account#1> show utxo                                                                                                                                                                                    
---                                                                                                                                                                                                     
- type: unspent_info
...

---
- account_id: "1"
  type: unspent_info
  public_payments:
    - utxo: e962d8fd7e031fa50e4f6dc3ee7a126d9f2d87a95415397c7370181467899182
      amount: 29411764705
      locked_timestamp: ~
  payments:
    - utxo: cb2311dedaf121d360e9ce382501da013f6b93d6049a3253dc399933cece7876
      amount: 1
      comment: ""
      locked_timestamp: ~
      recipient: 7ewZB7ECBkEgBaug1uPLXV8X4S3Beo3P7RgDA3PaFSjdVh5eDMu
      is_change: false
    - utxo: 5b540719cd8fcaa80231e7eb9ea18d37ffa8322051dda727e2c984548cb3aa3a
      amount: 1059367445999
      comment: Change <!---
      locked_timestamp: ~
      recipient: 7ewZB7ECBkEgBaug1uPLXV8X4S3Beo3P7RgDA3PaFSjdVh5eDMu
      is_change: false    <!---
```
