### ISSUE TITLE
Unnecessary zero-valued UTXO is created on "unstake all"

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#1276]
```
account#1> unstake                                                                                                                                                                                      
---                                                                                                                                                                                                     
- type: unstake_all
  payment_fee: 1000
...

---
- account_id: "1"
  type: transaction_created
  tx_hash: 7409d2b31e1407d08607eadec98e16d6bdc255a189d42c733134d430e61a5f04
  fee: 1000
  outputs:
    - output_type: payment  <!-- Remove this output
      utxo: 2b374d403c6315004b7171210da1c400a2068fe273700e09c2161e6005815567
      amount: 0 
      comment: Change for stake.
      locked_timestamp: ~
      recipient: 7ewZB7ECBkEgBaug1uPLXV8X4S3Beo3P7RgDA3PaFSjdVh5eDMu
      is_change: false
```
