### ISSUE TITLE
Restaking enabled, but node failed to restake utxo.

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#1482]
```
   stakes:
     - output_hash: 2da4bd3eb6ad26b1e8a33b5b5075a9e5f9b0d4599c38a0be957f7b18d5088af9
       account_pkey: stg1sc6shpexa0ypamf363wf843ye54tesymwc505ztky7fvepk5fd7q33et6c
       active_until_epoch: 10206
       is_active: true
       amount: 76735151180
     - output_hash: ca666ae67e88d4024454fe6fef412100370ba4d26e9909e4a51552149737c901
       account_pkey: stg1sc6shpexa0ypamf363wf843ye54tesymwc505ztky7fvepk5fd7q33et6c
       active_until_epoch: 8502
       is_active: false
       amount: 20000000000000
     - output_hash: 57da63f58c6973f16a4214bb8ff2ed3a89506e39fba801bbd27207a6f1ef3243
       account_pkey: stg1sc6shpexa0ypamf363wf843ye54tesymwc505ztky7fvepk5fd7q33et6c
       active_until_epoch: 10202
       is_active: true
       amount: 20000192039000
     - output_hash: 7f428a823f480581425d46a97d0d04c9e8d453db881fcb70bf29d58f6bfd1315
       account_pkey: stg1sc6shpexa0ypamf363wf843ye54tesymwc505ztky7fvepk5fd7q33et6c
       active_until_epoch: 10209
       is_active: true
       amount: 1161319945190
 ...
```
